### ISSUE TITLE
Excuse Command

### ISSUE THREAD

**Issue by IamRyven** [Educorreia932/Teacher-Bot#3]
A command that will show a random excuse for not finishing your homework

Example: **“Ahh, I thought it was in my bag, but it looks like I’ve left it at home by accident!”** – Of course you left it at home by accident! This one is a great excuse, it’s worked a fair few times for me, anyway…

**Comment by raymag** [comment]
Doing it.

**Comment by Educorreia932** [comment]
Save the excuses in an external file, instead of hardcoding it

**Comment by raymag** [comment]
I think it's okay now
